name: build
on: [push, pull_request]
jobs:
  racket-package-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jackfirth/racket-package-ci-action@v0.1.4
        with:
          name: runomatic
